deploy-develop:
  image: groupbwt/gitlab-runner-envoy-node:latest
  script:
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - current_dir=$(pwd)
    - remove_dir=$(date +'%m%d%Y%H%M%S')
    - scp -r "$current_dir" "$SSH_USER_NAME_ALTER"@185.224.138.7:"$SERVER_DIR_ALTER"/releases/"$remove_dir"
    - envoy run deploy --remove_dir="$remove_dir" --server_dir="$SERVER_DIR_ALTER"
  only:
    refs:
      - branches
    variables:
      - $CI_COMMIT_REF_NAME == $AUTO_DEPLOY_BRANCH_ALTER


deploy:
  image: groupbwt/gitlab-runner-envoy-node:latest
  script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - current_dir=$(pwd)
    - remove_dir=$(date +'%m%d%Y%H%M%S')
    - scp -r "$current_dir" "$SSH_USER_NAME_ALTER"@185.224.138.7:"$SERVER_DIR_ALTER"/releases/"$remove_dir"
    - envoy run deploy --remove_dir="$remove_dir" --server_dir="$SERVER_DIR_ALTER"
  except:
    - develop
  when: manual
