deploy-develop:
  image: groupbwt/gitlab-runner-envoy-node:latest
  script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - current_dir=$(pwd)
    - remove_dir=$(date +'%m%d%Y%H%M%S')
    - scp -r "$current_dir" "$SSH_USER_NAME"@77.121.81.204:"$SERVER_DIR"/releases/"$remove_dir"
    - envoy run deploy --remove_dir="$remove_dir" --server_dir="$SERVER_DIR"
  only:
    refs:
      - branches
    variables:
      - $CI_COMMIT_REF_NAME == $AUTO_DEPLOY_BRANCH


deploy:
  image: groupbwt/gitlab-runner-envoy:latest
  script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - current_dir=$(pwd)
    - remove_dir=$(date +'%m%d%Y%H%M%S')
    - scp -r "$current_dir" "$SSH_USER_NAME"@77.121.81.204:"$SERVER_DIR"/releases/"$remove_dir"
    - envoy run deploy --remove_dir="$remove_dir" --server_dir="$SERVER_DIR"
  except:
    - develop
  when: manual
